vespa-engine/docker-image

- include/start-container.sh
> Fix env variable name and start services on config server.

- Dockerfile
- LICENSE
- bin/tag-and-push-release.sh
- include/start-container.sh
> Add copyright header to files.

- Dockerfile
> Add git and network utils.

- README.md
> The contents of README.md automatically populates the description.

- Dockerfile
@aressem This reduced the image size by 25%
> Add yum clean to remove temporary yum files in docker image

- include/start-container.sh
Copy of https://github.com/vespa-engine/vespa/blob/573e322c1ac89e4c8b9f5a7f9e9784c23db2a2f0/vespabase/src/vespa-start-configserver.sh#L4:L71
> Source env first 

- include/start-container.sh
Reverts vespa-engine/docker-image#13
> Revert "Set VESPA_HOME"

- Dockerfile
@aressem Please review. Adds approx 1Gb to image.
> Add dependencies for tensorflow to onnx conversion

- include/start-container.sh
> Only set the VESPA_CONFIGSERVERS if not set.

- include/start-container.sh
@toregge please review
@jobergum FYI
> perform graceful shutdown when signaled

- Dockerfile
- screwdriver.yaml
> Container image build and publish on cd.screwdriver.cd with exact version

- screwdriver.yaml
> Remove workaround using current image.

- Dockerfile
> Add sudo and reduce image size by ~10%

- Dockerfile
- Dockerfile.stream8
- bin/tag-and-push-release.sh
- include/start-container.sh
> Add version for CentOS Stream 8

- include/start-container.sh
> Don't chown what is installed by RPMs.

- Dockerfile
> Skip weak deps.

- include/start-container.sh
- as this is not an important fix, we can hold off merge until next week
> Add explicit start of both configserver + services

- Dockerfile
> we only need git-core

- Dockerfile
> Use latest OpenJDK versions in image.

- Dockerfile
> Update OpenJDK in the same layer as installing the rest of the RPMs.

- Dockerfile.minimal
> Add Dockerfile for minimal image derived from scratch

- include/start-container.sh
@toregge please review
@kkraune FYI
> try to avoid changing hostname when not needed (or possible)

- include/start-container.sh
@aressem please review
@kkraune FYI
> run logfmt in background to make "trap" work

- Dockerfile
> Fix missing dnf plugins in CentOS Stream 8 base image

- Dockerfile
> Don't install anything else than what Vespa depends on via RPM.

- experimental/gpu-setup-rhel8-x86.sh
- experimental/gpu-setup-rhel9-x86.sh
@mpolden or @ean please review
> add GPU setup scripts for rhel8/rhel9

- experimental/gpu-setup-rhel8-x86.sh
- experimental/gpu-setup-rhel9-x86.sh
@kkraune / @mpolden please review
> bump versions (make it work on rocky 8.8)

- Dockerfile
> Default to el8 base image.

- Dockerfile
- Dockerfile.minimal
> Correct labels and minimal image after AlmaLinux transition.

- experimental/gpu-setup-rhel8-x86.sh
- experimental/gpu-setup-rhel9-x86.sh
> fix outdated cuda install

- include/start-container.sh
* vespa no longer starts privileged, remove old code
* the warning given here isn't really informative or useful
@kkraune please review
> remove hostname checks

- Dockerfile
> Make it optional to use local RPM repo.

- .github/workflows/mend.yaml
> feat: add Mend CLI scan workflow

- .github/workflows/mend.yaml
> Force reachability scan

- .github/workflows/mend.yaml
Disable Mend workflow
The PoV is over, we'll evaluate the findings and take decisions accordingly.
> fix(ci): Disable mend workflow

- include/start-container.sh
> Add container memory check at startup
